name: pubspec_yaml_2
description: Dart library to access and manipulate content of pubspec.yaml files
version: 3.3.0
homepage: https://github.com/greymag/pubspec_yaml
repository: https://github.com/greymag/pubspec_yaml
issue_tracker: https://github.com/greymag/pubspec_yaml/issues

environment:
  sdk: '>=2.14.0 <4.0.0'

dependencies:
  collection: ^1.18.0
  functional_data: ^1.2.0
  json2yaml: ^3.0.1
  meta: ^1.7.0
  sum_types: ^0.4.0
  yaml: ^3.1.0

dev_dependencies:
  build_runner: ^2.4.9
  dependency_validator: ^4.1.2
  functional_data_generator: ^1.1.0
  innim_lint: ^0.5.0+1
  sum_types_generator: ^0.4.0
  test: ^1.25.7
